// <auto-generated />
namespace Module6TP1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class REQUIRED_NOM_ARTMARTIAL : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(REQUIRED_NOM_ARTMARTIAL));
        
        string IMigrationMetadata.Id
        {
            get { return "202004220814550_REQUIRED_NOM_ARTMARTIAL"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
